name: ðŸ¤–ðŸ‘ŒðŸ¤–
on: pull_request

jobs:
  judge-dependabot:
    permissions:
      contents: read
      pull-requests: read
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    outputs:
      merge: ${{ steps.conclusion.outputs.merge }}
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: dependabot
        uses: dependabot/fetch-metadata@21025c705c08248db411dc16f3619e6b5f9ea21a # v2.5.0
      - name: Judge
        id: conclusion
        if: >-
          steps.dependabot.outputs.update-type != 'version-update:semver-major' ||
          contains(steps.dependabot.outputs.dependency-names, 'cachix')
        run: echo -n 'merge=true' | tee -a "$GITHUB_OUTPUT"
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    needs: [judge-dependabot]
    if: ${{ needs.judge-dependabot.outputs.merge == 'true' }}
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    steps:
      # Required for checkout before referring to your own action as `uses: ./`.
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Wait other jobs
        uses: ./
        timeout-minutes: 10
        with:
          skip-same-workflow: 'true'
      - name: Approve and merge
        run: gh pr review --approve "$PR_URL" && gh pr merge --auto --squash --delete-branch "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Avoid `automerge` renovate official feature.
  #   It wait longtime to be merged.
  # Avoid `platformAutomerge` renovate official feature.
  #   It requires many changes in GitHub settings.
  #    - `Allow auto-merge`
  #    - `Require status checks to pass before merging` and specify the status names
  #   Changing in all personal repository is annoy task for me. Even if using terrafform, getting mandatory CI names in each repo is too annoy!
  renovate:
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    if: ${{ github.actor == 'renovate[bot]' }}
    steps:
      # Required for checkout before referring to your own action as `uses: ./`.
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Wait other jobs
        uses: ./
        timeout-minutes: 10
        with:
          retry-method: 'equal_intervals'
          minimum-interval: 'PT15S'
          skip-same-workflow: 'true'
      - name: Approve and merge
        run: gh pr review --approve "$PR_URL" && gh pr merge --auto --squash --delete-branch "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # https://github.com/kachick/anylang-template/issues/51
  selfup-runner:
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    if: ${{ github.actor == 'selfup-runner[bot]' }}
    steps:
      # Required for checkout before referring to your own action as `uses: ./`.
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Wait other jobs
        uses: ./
        timeout-minutes: 20
        with:
          skip-same-workflow: 'true'
      - name: Approve and merge
        run: gh pr review --approve "$PR_URL" && gh pr merge --auto --delete-branch --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
